#ifndef _INC_P10MATRIX_CONF_H
#define _INC_P10MATRIX_CONF_H

#define P10_PANELS_X    1
#define P10_PANELS_Y    1

#define P10_PANEL_DOTS_X    32
#define P10_PANEL_DOTS_Y    16

#define P10_PANEL_STRIPS_X  (P10_PANEL_DOTS_X / 8)
#define P10_PANEL_STRIPS_Y  (P10_PANEL_DOTS_Y)

#define P10_STRIPS_X    (P10_PANEL_STRIPS_X * P10_PANELS_X)
#define P10_STRIPS_Y    (P10_PANEL_STRIPS_Y * P10_PANELS_Y)

#endif // _INC_P10MATRIX_CONF_H